import { LlmService } from "./llm.service";

/**
 * Lead Discovery Engine — real web prospecting without paid data APIs.
 *
 * Pipeline: query plan → web search (DuckDuckGo HTML) → site scraping →
 * structured extraction (JSON-LD / microdata / regex) → LLM enrichment when
 * a provider is configured → scored `DiscoveredLead`s ready for CRM import.
 *
 * Every network call is timeout-bounded and fails soft: partial results are
 * returned with an honest `notes` trail instead of throwing.
 */

export interface DiscoveredLead {
  companyName: string;
  website: string | null;
  industry: string | null;
  location: string | null;
  size: string | null;
  description: string | null;
  emails: string[];
  phones: string[];
  socials: { linkedin?: string; twitter?: string };
  sourceQuery: string;
  sourceUrl: string | null;
  fitScore: number; // 0-100, heuristic + LLM blend
  fitReason: string;
  contactHint: string | null;
}

export interface DiscoveryResult {
  success: boolean;
  query: string;
  leads: DiscoveredLead[];
  llmUsed: boolean;
  notes: string[];
}

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36";
const FETCH_TIMEOUT = 12_000;

export class LeadDiscoveryService {
  /** Full pipeline: natural-language ask → discovered, scored leads. */
  static async discover(request: {
    query: string;
    industry?: string;
    location?: string;
    maxResults?: number;
  }): Promise<DiscoveryResult> {
    const maxResults = Math.min(Math.max(request.maxResults ?? 6, 1), 10);
    const notes: string[] = [];

    // 1. Optional LLM query planning (expands the ask into sharp search queries)
    const plan = await LeadDiscoveryService.planQueries(request);
    const queries = plan.queries.length > 0 ? plan.queries : [LeadDiscoveryService.fallbackQuery(request)];
    if (plan.llmUsed) notes.push("Query plan generated by LLM.");
    else notes.push("Using heuristic query plan (no LLM provider configured).");

    // 2. Web search across the planned queries
    const searchHits = await LeadDiscoveryService.webSearch(queries, maxResults * 2);
    if (searchHits.length === 0) {
      notes.push("Web search returned no usable results for these queries.");
      return { success: false, query: request.query, leads: [], llmUsed: plan.llmUsed, notes };
    }
    notes.push(`Found ${searchHits.length} candidate sites from web search.`);

    // 3. Scrape each candidate homepage (bounded concurrency)
    const scraped = await LeadDiscoveryService.scrapeAll(searchHits.slice(0, maxResults + 2));

    // 4. Extract structured data per site
    let discovered = scraped
      .map((s) => LeadDiscoveryService.extract(s, request))
      .filter((l): l is DiscoveredLead => l !== null);

    // 5. Optional LLM enrichment: ICP fit scoring + tidy descriptions
    let llmUsed = plan.llmUsed;
    if (LlmService.getStatus().available && discovered.length > 0) {
      const enriched = await LeadDiscoveryService.enrichBatch(discovered, request);
      if (enriched) {
        discovered = enriched;
        llmUsed = true;
        notes.push("Fit scores refined by LLM.");
      } else {
        notes.push("LLM enrichment unavailable — using heuristic fit scores.");
      }
    } else {
      notes.push("Fit scores computed heuristically (add an LLM key for sharper ICP scoring).");
    }

    // 6. Rank and trim
    discovered.sort((a, b) => b.fitScore - a.fitScore);
    return {
      success: discovered.length > 0,
      query: request.query,
      leads: discovered.slice(0, maxResults),
      llmUsed,
      notes,
    };
  }

  // --- Step 1: query planning ------------------------------------------------

  private static async planQueries(request: {
    query: string;
    industry?: string;
    location?: string;
  }): Promise<{ queries: string[]; llmUsed: boolean }> {
    if (!LlmService.getStatus().available) {
      return { queries: [], llmUsed: false };
    }
    const result = await LlmService.completeJson(
      'You are a B2B prospecting research assistant. Turn the user\'s target description into 2-3 precise web search queries that would surface real company websites (not directories, not news). Respond with JSON: {"queries": ["...", "..."]}',
      `Target: ${request.query}${request.industry ? `\nIndustry: ${request.industry}` : ""}${request.location ? `\nLocation: ${request.location}` : ""}`
    );
    if (!result.ok || !result.text) return { queries: [], llmUsed: false };
    const parsed = LlmService.parseJsonLoose(result.text);
    const queries = Array.isArray(parsed?.queries)
      ? (parsed.queries as unknown[]).filter((q): q is string => typeof q === "string" && q.length > 2).slice(0, 3)
      : [];
    return { queries, llmUsed: queries.length > 0 };
  }

  private static fallbackQuery(request: { query: string; industry?: string; location?: string }): string {
    const parts = [request.query, request.industry, request.location].filter(Boolean);
    return parts.join(" ").trim();
  }

  // --- Step 2: web search ------------------------------------------------------

  private static async webSearch(queries: string[], limit: number): Promise<{ url: string; title: string }[]> {
    const hits: { url: string; title: string }[] = [];
    const seen = new Set<string>();

    await Promise.all(
      queries.map(async (q) => {
        try {
          const res = await fetch(`https://html.duckduckgo.com/html/?q=${encodeURIComponent(q)}`, {
            headers: { "User-Agent": UA, "Accept-Language": "en-US,en;q=0.9" },
            signal: AbortSignal.timeout(FETCH_TIMEOUT),
          });
          if (!res.ok) return;
          const html = await res.text();
          // Result links: direct hrefs or DDG-wrapped //duckduckgo.com/l/?uddg=<enc>
          const linkRe = /<a[^>]+class="[^"]*result__a[^"]*"[^>]*href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/g;
          let m: RegExpExecArray | null;
          while ((m = linkRe.exec(html)) !== null && hits.length < limit * 2) {
            let url = m[1];
            const uddg = /[?&]uddg=([^&]+)/.exec(url);
            if (uddg) url = decodeURIComponent(uddg[1]);
            url = url.startsWith("//") ? `https:${url}` : url;
            if (!/^https?:\/\//.test(url)) continue;
            const host = LeadDiscoveryService.hostOf(url);
            if (!host || seen.has(host)) continue;
            // Skip aggregator/directory domains — we want actual company sites
            if (/duckduckgo|wikipedia\.org|linkedin\.com|facebook\.com|youtube\.com|reddit\.com|yelp\.com|bloomberg\.com|crunchbase\.com|glassdoor\.com|indeed\.com|zoominfo\.com|clutch\.co|trustpilot\.com|medium\.com|twitter\.com|x\.com|instagram\.com|github\.io?$/i.test(host)) continue;
            // Directory / listing / review aggregators — not real company sites
            if (/npino\.com|rankmydentist|healthgrades|zocdoc|opencare|threebestrated|yellowpages|whitepages|mapquest|alignable|porch\.com|angi\.com|thumbtack|birdeye|doctor\.com|ratemds|vitals\.com|usnews\.com|nicelocal|chamberofcommerce|find-open|bizapedia|manta\.com|hotfrog|brownbook|cylex|tupalo|cybo\.com|provenexpert|sitejabber|sourceforge|g2\.com|capterra|producthunt|goodfirms|designrush|upwork|fiverr|clutch\.co|superpages|comfy\.com|opendius|locanto|olsx|classifieds/i.test(host)) continue;
            seen.add(host);
            hits.push({ url, title: LeadDiscoveryService.stripTags(m[2]) });
          }
        } catch {
          // search engine failed for this query — others may still succeed
        }
      })
    );
    return hits.slice(0, limit);
  }

  // --- Step 3: scraping ---------------------------------------------------------

  private static async scrapeAll(hits: { url: string; title: string }[]) {
    const results = await Promise.allSettled(
      hits.map(async (hit) => {
        try {
          const res = await fetch(hit.url, {
            headers: { "User-Agent": UA, Accept: "text/html,application/xhtml+xml" },
            signal: AbortSignal.timeout(FETCH_TIMEOUT),
            redirect: "follow",
          });
          if (!res.ok) return null;
          const contentType = res.headers.get("content-type") || "";
          if (!contentType.includes("html")) return null;
          // Cap body size — parse only the first ~300KB
          const html = (await res.text()).slice(0, 300_000);
          return { entryUrl: hit.url, searchTitle: hit.title, html, finalUrl: res.url };
        } catch {
          return null;
        }
      })
    );
    return results
      .map((r) => (r.status === "fulfilled" ? r.value : null))
      .filter((v): v is { entryUrl: string; searchTitle: string; html: string; finalUrl: string } => v !== null);
  }

  // --- Step 4: extraction ---------------------------------------------------------

  private static extract(
    site: { entryUrl: string; searchTitle: string; html: string; finalUrl: string },
    request: { query: string; industry?: string; location?: string }
  ): DiscoveredLead | null {
    const host = LeadDiscoveryService.hostOf(site.finalUrl) || LeadDiscoveryService.hostOf(site.entryUrl);
    if (!host) return null;

    const title =
      LeadDiscoveryService.metaContent(site.html, "og:site_name") ||
      LeadDiscoveryService.metaContent(site.html, "og:title") ||
      /<title[^>]*>([\s\S]*?)<\/title>/i.exec(site.html)?.[1]?.trim() ||
      site.searchTitle;
    const companyName = LeadDiscoveryService.stripTags(title).split(/[|\-–—·]/)[0].trim() || host;

    const description =
      LeadDiscoveryService.metaContent(site.html, "description") ||
      LeadDiscoveryService.metaContent(site.html, "og:description");

    // JSON-LD structured data
    const jsonLd = LeadDiscoveryService.parseJsonLd(site.html);
    const org = jsonLd.find((o) => /organization|localbusiness|corporation|company|store|restaurant|agency/i.test(o.type));

    const emails = LeadDiscoveryService.extractEmails(site.html);
    const phones = LeadDiscoveryService.extractPhones(site.html);
    const socials = {
      linkedin: /https?:\/\/(?:[a-z]{2,3}\.)?linkedin\.com\/company\/[a-z0-9%_-]+/i.exec(site.html)?.[0],
      twitter: /https?:\/\/(?:www\.)?(?:twitter\.com|x\.com)\/[A-Za-z0-9_]+/i.exec(site.html)?.[0],
    };

    const location =
      org?.address ||
      LeadDiscoveryService.metaContent(site.html, "geo:region") ||
      LeadDiscoveryService.addressFromHtml(site.html) ||
      request.location ||
      null;

    const industry = org?.industry || request.industry || null;
    const size = org?.size || null;

    // Heuristic ICP fit: signal density on the page
    let fitScore = 35;
    const reasons: string[] = [];
    if (emails.length > 0) { fitScore += 15; reasons.push("public contact email"); }
    if (phones.length > 0) { fitScore += 8; reasons.push("phone listed"); }
    if (socials.linkedin) { fitScore += 7; reasons.push("LinkedIn presence"); }
    if (description && description.length > 60) { fitScore += 8; reasons.push("substantive positioning"); }
    if (org) { fitScore += 7; reasons.push("structured org data"); }
    const buyerWords = /software|platform|agency|consult|services|solutions|digital|studio|labs|group|systems|technologies/i;
    if (buyerWords.test(companyName) || (description && buyerWords.test(description))) { fitScore += 10; reasons.push("likely services/tech buyer"); }
    if (request.industry && industry && new RegExp(request.industry.split(/[\s,]+/)[0], "i").test(`${companyName} ${industry} ${description ?? ""}`)) {
      fitScore += 10; reasons.push(`matches ${request.industry}`);
    }

    return {
      companyName: companyName.slice(0, 120),
      website: `https://${host}`,
      industry,
      location,
      size,
      description: description ? LeadDiscoveryService.stripTags(description).slice(0, 400) : null,
      emails: [...new Set(emails)].slice(0, 4),
      phones: [...new Set(phones)].slice(0, 3),
      socials,
      sourceQuery: request.query,
      sourceUrl: site.finalUrl,
      fitScore: Math.min(fitScore, 96),
      fitReason: reasons.slice(0, 3).join(", ") || "baseline web presence",
      contactHint: emails[0] ?? phones[0] ?? null,
    };
  }

  // --- Step 5: LLM enrichment ------------------------------------------------------

  private static async enrichBatch(
    leads: DiscoveredLead[],
    request: { query: string; industry?: string; location?: string }
  ): Promise<DiscoveredLead[] | null> {
    const result = await LlmService.completeJson(
      `You are an ICP (ideal customer profile) analyst for a B2B agency. For each discovered company, estimate fitScore 0-100 for the stated target and write a one-sentence fitReason. Never invent contact details that aren't present. Respond with JSON: {"companies":[{"index":0,"fitScore":72,"fitReason":"..."}]}`,
      `Target profile: ${request.query}\n\nCompanies:\n${leads
        .map(
          (l, i) =>
            `[${i}] ${l.companyName} | site: ${l.website ?? "none"} | industry: ${l.industry ?? "?"} | location: ${l.location ?? "?"} | about: ${l.description ?? "?"} | contacts found: ${l.emails.concat(l.phones).join(", ") || "none"}`
        )
        .join("\n")}`
    );
    if (!result.ok || !result.text) return null;
    const parsed = LlmService.parseJsonLoose(result.text);
    if (!parsed || !Array.isArray(parsed.companies)) return null;
    const updates = parsed.companies as { index?: number; fitScore?: number; fitReason?: string }[];
    const next = [...leads];
    for (const u of updates) {
      if (typeof u.index !== "number" || !next[u.index]) continue;
      if (typeof u.fitScore === "number" && u.fitScore >= 0 && u.fitScore <= 100) {
        next[u.index] = { ...next[u.index], fitScore: Math.round(u.fitScore) };
      }
      if (typeof u.fitReason === "string" && u.fitReason.length > 3) {
        next[u.index] = { ...next[u.index], fitReason: u.fitReason.slice(0, 200) };
      }
    }
    return next;
  }

  /** Deep-dive a single URL (used by the copilot's "research this site" path). */
  static async researchUrl(url: string): Promise<DiscoveredLead | null> {
    const results = await LeadDiscoveryService.scrapeAll([{ url, title: url }]);
    if (results.length === 0) return null;
    return LeadDiscoveryService.extract(results[0], { query: url });
  }

  // --- parsing helpers -----------------------------------------------------------

  private static hostOf(url: string): string | null {
    try {
      return new URL(url).hostname.replace(/^www\./, "");
    } catch {
      return null;
    }
  }

  private static stripTags(html: string): string {
    return html
      .replace(/<[^>]+>/g, " ")
      .replace(/&amp;/g, "&")
      .replace(/&quot;/g, '"')
      .replace(/&#39;/g, "'")
      .replace(/&lt;/g, "<")
      .replace(/&gt;/g, ">")
      .replace(/&nbsp;/g, " ")
      .replace(/\s+/g, " ")
      .trim();
  }

  private static metaContent(html: string, name: string): string | null {
    const re = new RegExp(
      `<meta[^>]+(?:name|property)=["']${name.replace(/[.*+?^${}()|[\\]\\\\]/g, "\\\\$&")}["'][^>]*>`,
      "i"
    );
    const tag = re.exec(html)?.[0];
    if (!tag) return null;
    const content = /content=["']([^"']*)["']/i.exec(tag)?.[1];
    return content ? this.stripTags(content) : null;
  }

  private static parseJsonLd(html: string): { type: string; industry?: string; address?: string; size?: string }[] {
    const out: { type: string; industry?: string; address?: string; size?: string }[] = [];
    const re = /<script[^>]+application\/ld\+json[^>]*>([\s\S]*?)<\/script>/gi;
    let m: RegExpExecArray | null;
    while ((m = re.exec(html)) !== null && out.length < 5) {
      try {
        const parsed: unknown = JSON.parse(m[1].trim());
        const nodes = Array.isArray(parsed) ? parsed : [parsed];
        for (const node of nodes) {
          if (typeof node !== "object" || node === null) continue;
          const obj = node as Record<string, unknown>;
          const type = String(obj["@type"] ?? "");
          const address =
            typeof obj.address === "object" && obj.address !== null
              ? String((obj.address as Record<string, unknown>).addressLocality ?? "") +
                ", " +
                String((obj.address as Record<string, unknown>).addressRegion ?? "")
              : typeof obj.address === "string"
                ? obj.address
                : undefined;
          const numberOfEmployees =
            typeof obj.numberOfEmployees === "object" && obj.numberOfEmployees !== null
              ? String((obj.numberOfEmployees as Record<string, unknown>).value ?? "")
              : typeof obj.numberOfEmployees === "string"
                ? obj.numberOfEmployees
                : undefined;
          out.push({
            type,
            industry: typeof obj.industry === "string" ? obj.industry : undefined,
            address: address?.replace(/^[,\s]+|[,\s]+$/g, "") || undefined,
            size: numberOfEmployees || undefined,
          });
        }
      } catch {
        // malformed JSON-LD — skip
      }
    }
    return out;
  }

  private static extractEmails(html: string): string[] {
    const emails = new Set<string>();
    const mailtoRe = /mailto:([^"'?>\s]+)/gi;
    let m: RegExpExecArray | null;
    while ((m = mailtoRe.exec(html)) !== null) {
      const e = decodeURIComponent(m[1]).trim();
      if (/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(e) && !/\.(png|jpg|jpeg|gif|webp|svg)$/i.test(e)) emails.add(e.toLowerCase());
    }
    const textRe = /\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b/g;
    const text = html.replace(/<[^>]+>/g, " ");
    const seenInText = text.match(textRe) ?? [];
    for (const e of seenInText) {
      if (!/example\.com|sentry\.io|domain\.com|email\.com|your(e?mail)?|test@/i.test(e)) emails.add(e.toLowerCase());
    }
    return [...emails];
  }

  private static extractPhones(html: string): string[] {
    const phones = new Set<string>();
    const telRe = /tel:([+0-9()\-.\s]{7,25})/gi;
    let m: RegExpExecArray | null;
    while ((m = telRe.exec(html)) !== null) {
      const cleaned = m[1].replace(/[^\d+]/g, "");
      if (cleaned.length >= 7 && cleaned.length <= 15) phones.add(cleaned);
    }
    return [...phones];
  }

  private static addressFromHtml(html: string): string | null {
    const re = /<(?:address|div|span|p)[^>]+(?:class|itemprop)=["'][^"']*(?:address|addr)[^"']*["'][^>]*>([\s\S]{5,200}?)<\/(?:address|div|span|p)>/gi;
    const m = re.exec(html);
    return m ? this.stripTags(m[1]).slice(0, 120) : null;
  }
}
